package abrirChamados;

import java.awt.event.ActionListener;
import javax.swing.Action;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import classes.Chamados;
import classes.Usuario;
import telaChamado.telaChamado;
import javax.swing.JOptionPane;

import java.util.regex.Pattern;
import java.util.regex.Matcher;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author renan.losantos
 */
public class abrirChamado extends javax.swing.JFrame {

    /**
     * Creates new form abrirChamado
     */
    public abrirChamado() {
        initComponents();

        btnCriar.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                Chamados chamados = new Chamados();
                Usuario usuario = new Usuario();

                String patrimonioText = textAreaPatri.getText().trim(); // Obter e remover espaços

                // Verificar se a entrada do patrimônio está vazia
                if (patrimonioText.isEmpty()) {
                    JOptionPane.showMessageDialog(null, "Erro ao criar chamado, patrimônio nulo!!!", "Atenção", JOptionPane.ERROR_MESSAGE);
                    return;
                }
                
                // Validação do comprimento do patrimônio como inteiro e se é só numero
                if (patrimonioText.length() > 15) {
                    JOptionPane.showMessageDialog(null, "O máximo é 15 caracteres para o patrimônio.", "Atenção", JOptionPane.ERROR_MESSAGE);
                    return;
                } else if(!Pattern.matches("\\d+", patrimonioText.trim())){
                    JOptionPane.showMessageDialog(null, "o patrimônio deve conter apenas números!", "Atenção", JOptionPane.ERROR_MESSAGE);
                }

                int patrimonio;

                try {
                    patrimonio = Integer.parseInt(patrimonioText);
                } catch (NumberFormatException ex) {
                    JOptionPane.showMessageDialog(null, "Erro ao criar chamado, patrimônio inválido!!!", "Atenção", JOptionPane.ERROR_MESSAGE);
                    return;
                }


                // Verificar se a entrada do problema está vazia
                if (textAreaProblema.getText().trim().isEmpty()) {
                    JOptionPane.showMessageDialog(null, "Erro ao criar chamado, descrição nula!!!", "Atenção", JOptionPane.ERROR_MESSAGE);
                    return;
                }

                if (textAreaProblema.getText().length() < 12) {
                    JOptionPane.showMessageDialog(null, "O minimo é 15", "Atenção", JOptionPane.ERROR_MESSAGE);
                    return;
                } else if (textAreaProblema.getText().length() > 255) {
                    JOptionPane.showMessageDialog(null, "O maximo é 255", "Atenção", JOptionPane.ERROR_MESSAGE);
                    return;
                }
                

                chamados.CriarChamados(patrimonio, textAreaProblema.getText(), usuario.idTecnico);
                JOptionPane.showMessageDialog(null, "Chamado cadastrado com sucesso, por favor, aguarde um técnico.", "Atenção", JOptionPane.INFORMATION_MESSAGE);
                telaChamado mainpage = new telaChamado();
                mainpage.abrirTela();
                dispose();

            }
        });

        btnVoltar.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                telaChamado mainpage = new telaChamado();
                mainpage.abrirTela();
                dispose();

            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtCriarChamado = new javax.swing.JLabel();
        JavaLogo = new javax.swing.JLabel();
        txtProblema = new javax.swing.JLabel();
        txtPatri = new javax.swing.JLabel();
        textAreaProblema = new javax.swing.JFormattedTextField();
        textAreaPatri = new javax.swing.JFormattedTextField();
        btnVoltar = new javax.swing.JButton();
        btnCriar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(690, 290));
        setMinimumSize(new java.awt.Dimension(490, 420));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        txtCriarChamado.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtCriarChamado.setText("CRIAR CHAMADO");
        jPanel1.add(txtCriarChamado);
        txtCriarChamado.setBounds(140, 50, 210, 20);

        JavaLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-logo-java-coffee-cup-144.png"))); // NOI18N
        JavaLogo.setText("jLabel2");
        jPanel1.add(JavaLogo);
        JavaLogo.setBounds(170, 80, 130, 120);

        txtProblema.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtProblema.setText("Problema:");
        jPanel1.add(txtProblema);
        txtProblema.setBounds(110, 270, 70, 20);

        txtPatri.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtPatri.setText("Patrimônio:");
        jPanel1.add(txtPatri);
        txtPatri.setBounds(110, 210, 80, 20);
        jPanel1.add(textAreaProblema);
        textAreaProblema.setBounds(110, 290, 270, 30);
        jPanel1.add(textAreaPatri);
        textAreaPatri.setBounds(110, 230, 270, 30);

        btnVoltar.setBackground(new java.awt.Color(255, 204, 204));
        btnVoltar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnVoltar.setText("VOLTAR");
        btnVoltar.setBorder(null);
        jPanel1.add(btnVoltar);
        btnVoltar.setBounds(10, 10, 110, 20);

        btnCriar.setBackground(new java.awt.Color(244, 68, 52));
        btnCriar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCriar.setText("CRIAR");
        jPanel1.add(btnCriar);
        btnCriar.setBounds(170, 340, 150, 30);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Crie um chamado apartir do seu problema!");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(100, 390, 300, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 490, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
     public void abrirTela() {
        new abrirChamado().setVisible(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(abrirChamado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(abrirChamado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(abrirChamado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(abrirChamado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new abrirChamado().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JavaLogo;
    private javax.swing.JButton btnCriar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JFormattedTextField textAreaPatri;
    private javax.swing.JFormattedTextField textAreaProblema;
    private javax.swing.JLabel txtCriarChamado;
    private javax.swing.JLabel txtPatri;
    private javax.swing.JLabel txtProblema;
    // End of variables declaration//GEN-END:variables
}
